spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/interface-open?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: dust0000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  aop:
    auto: true
  # redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    #password:
    lettuce:
      pool:
        max-wait: -1
        max-idle: 5
        min-idle: 0
        max-active: 20
  redisson:
    #password: password # Redisson 的密码配置（选填）
    single-server-config:
      address: redis://127.0.0.1:6379 # Redisson 连接地址
      database: 0 # Redis 数据库编号，从 0 开始
      timeout: 3000 # Redis 超时时间，单位为毫秒
# 日志配置
logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-default-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

